spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaojingyuan/springcloud
#          searchPaths: subdir
          username:
          password:
      label: master
server:
  port: 8010